// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char GPRS_APN[]      = SECRET_OPTIONAL_APN;
const char PINNUMBER[]     = SECRET_OPTIONAL_PIN;
const char GPRS_LOGIN[]    = SECRET_OPTIONAL_USERNAME;
const char GPRS_PASSWORD[] = SECRET_OPTIONAL_PASSWORD;


CloudTemperatureSensor temperature;
CloudTemperatureSensor waterTemp;
int tDS;
CloudRelativeHumidity humidity;

void initProperties(){

  ArduinoCloud.addProperty(temperature, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(waterTemp, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(tDS, READ, 10 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 10 * SECONDS, NULL);

}

NBConnectionHandler ArduinoIoTPreferredConnection(PINNUMBER, GPRS_APN, GPRS_LOGIN, GPRS_PASSWORD);